services:
  - type: web
    name: brickify-api
    env: python
    region: frankfurt  # Europe pour une meilleure latence
    plan: pro  # Plan avec GPU
    buildCommand: |
      /opt/render/project/src/.venv/bin/python3.9 -m pip install --upgrade pip
      pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
      chmod +x backend/install_pytorch3d.sh
      sudo ./backend/install_pytorch3d.sh
      pip install -r backend/requirements.txt
    startCommand: chmod +x backend/start.sh && ./backend/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: STORAGE_PATH
        value: /data/storage
      - key: MAX_MEMORY_MB
        value: 16384  # 16GB RAM
      - key: MAX_STORAGE_GB
        value: 50  # 50GB Storage
      - key: CLEANUP_INTERVAL_MINS
        value: 30
      - key: MAX_TEMP_FILES
        value: 1000
      - key: MAX_FILE_AGE_HOURS
        value: 24
      - key: DEVICE
        value: cuda
      - key: NUM_WORKERS
        value: 4
      - key: BATCH_SIZE
        value: 32
      - key: PRECISION
        value: float16
    disk:
      name: data
      mountPath: /data
      sizeGB: 50
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
    healthCheckPath: /health
    autoDeploy: true
    gpu:
      enabled: true
      type: t4  # NVIDIA T4 GPU

  - type: web
    name: brickify-ai-service
    env: docker
    region: frankfurt
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8001
      - key: DEVICE
        value: cpu
      - key: STORAGE_PATH
        value: /app/storage
      - key: CACHE_PATH
        value: /app/cache
      - key: MODELS_PATH
        value: /app/models
      - key: LOG_LEVEL
        value: info
      - key: NUM_WORKERS
        value: 2
      - key: BATCH_SIZE
        value: 16
    disk:
      name: storage
      mountPath: /app/storage
      sizeGB: 1 