services:
  - type: web
    name: brickify-ai-kfl2
    env: docker
    buildCommand: docker build -t brickify-ai-kfl2 -f ai/Dockerfile .
    startCommand: docker run -p 8000:8000 brickify-ai-kfl2
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: "3.9.0"