services:
  - type: web
    name: brickify-ai-kfl2
    env: docker
    rootDirectory: ai
    dockerfilePath: Dockerfile
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: "3.9.0"