from setuptools import setup, find_packages

setup(
    name="brickify-backend",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "python-multipart>=0.0.5",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "pydantic==1.8.2",
        "google-cloud-storage==2.5.0",
        "opencv-python-headless==4.7.0.72",
        "trimesh>=3.9.0",
        "numpy-stl==2.17.1",
        "python-dotenv==0.19.0",
        "aiofiles>=0.7.0",
        "pymongo==3.12.0",
        "motor==2.5.1",
        "sqlalchemy>=1.4.0",
        "psycopg2-binary==2.9.5",
        "requests==2.28.2",
        "pillow==9.5.0",
        "numpy>=1.21.0",
        "pandas==2.0.2",
        "scikit-learn==1.2.2",
        "tensorflow==2.12.0",
        "aiohttp==3.8.4",
        "firebase-admin==6.2.0",
        "boto3==1.26.137",
        "prometheus-client==0.17.1",
        "python-json-logger==2.0.7",
        "torch>=2.0.0",
        "torchvision==0.15.2",
        "reportlab==4.0.4",
        "colormath==3.0.0",
        "psutil>=5.8.0",
        "tqdm==4.65.0",
        "scipy==1.10.1",
        "matplotlib==3.7.1",
        "scikit-image==0.21.0",
        "open3d>=0.13.0",
        "bcrypt>=3.2.0",
        "alembic>=1.7.0",
        "asyncpg>=0.24.0",
        "pytest>=6.2.0",
        "pytest-asyncio>=0.15.0",
        "black>=21.7b0",
        "isort>=5.9.0",
        "flake8>=3.9.0"
    ],
    python_requires=">=3.9",
    author="merco69",
    author_email="contact@brickify.app",
    description="Backend pour l'application Brickify",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/merco69/brickify",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
    ],
) 