services:
  - type: web
    name: brickify-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        python3-dev \
        cmake \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        libegl1-mesa-dev \
        libxrandr-dev \
        libxinerama-dev \
        libxcursor-dev \
        libxi-dev
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: brickify-db
          property: connectionString

  - type: web
    name: brickify-ai
    env: docker
    dockerfilePath: ai_service/Dockerfile
    envVars:
      - key: PORT
        value: 8001