# Configuration du service d'apprentissage des modèles LEGO

# Paramètres du modèle
model:
  input_channels: 1
  hidden_channels: [32, 64, 128]
  kernel_size: 3
  padding: 1
  use_batch_norm: true
  dropout_rate: 0.2

# Paramètres d'entraînement
training:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 100
  early_stopping_patience: 10
  validation_split: 0.2

# Paramètres de données
data:
  voxel_size: 32
  normalize: true
  augmentation:
    enabled: true
    rotation_range: [-15, 15]
    scale_range: [0.9, 1.1]

# Paramètres de sauvegarde
storage:
  model_dir: "models"
  checkpoint_frequency: 10
  save_best_only: true

# Paramètres de logging
logging:
  level: "INFO"
  save_tensorboard: true
  metrics_frequency: 100

# Paramètres matériels
hardware:
  device: "cuda"  # ou "cpu"
  num_workers: 4
  pin_memory: true 